# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: 'Update release notes history'
on:
  release:
    types:
      - published
      
defaults:
  run:
    shell: pwsh

jobs:
  update_notes:
    name: 📜 update notes
    runs-on: ubuntu-latest
    steps:   
    - name: 🤘 checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: 🗎 create release notes      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_NAME: ${{ github.event.release.name }}
        RELEASE_BODY: ${{ github.event.release.body }}
      run: |   
        $NL = "`r`n`r`n"
        $name = $env:RELEASE_NAME
        $body = $env:RELEASE_BODY
        $releaseNumber = "${{ github.event.release.tag_name }}" 
        $publishedAt = [DateTime]::Parse("${{ github.event.release.published_at }}").ToUniversalTime().ToString('yyyy-MM-dd HH:mm:ss') + " GMT"
        $url = "${{ github.event.release.html_url }}"
        $authorLogin = "${{ github.event.release.author.login }}"
        $authorUrl = "${{ github.event.release.author.html_url }}" 

        $releaseNotes = "# Release $releaseNumber"
        
        if($name){
            $releaseNotes += " - $name"
        }
        $releaseNotes += $NL

        $releaseNotes += "Published [$publishedAt]($url) by [$authorLogin]($authorUrl)" + $NL + $NL

        if($body){
            $releaseNotes += "`r`n`r`n $body"
        }
        
        $releaseNotes += "$NL$NL$NL"
                
        $releaseNotes | Set-Content -Encoding UTF8 "ReleaseNotesFromLastRelease.md"

    - name: ⬆️ upload release notes 
      uses: actions/upload-artifact@v4
      with:
        name: ReleaseNotes
        if-no-files-found: error
        retention-days: 7
        path: ReleaseNotesFromLastRelease.md     
        
        
  deploy:   
      name: 🚀 create pull request      
      runs-on: ubuntu-latest
      needs: [ update_notes ]
      steps:
        - name: ⬇️ download notes
          uses: actions/download-artifact@v4
          with:
            name: ReleaseNotes
            path: .

        - name: create PR
          run: |
              $releaseNumber = "${{ github.event.release.tag_name }}"
              $branchName = "build/update-release-notes-$releaseNumber-$(Get-Date -Format "yyyyMMdd_HHmmss")"
                            
              git --version
              git config user.name "GitHub Actions Bot"
              git config user.email "<>"
              git status
              git tag
              git describe

              Write-Host $branchName 

              Get-Content -Encoding UTF8 "ReleaseNotesFromLastRelease.md" -Raw


              #git checkout -b $branchName
        
        
              
        
